let users = [
  {
    firstName: 'Hedy',
    lastName: 'Toope',
    email: 'htoope0@ucla.edu',
    gender: false,
    birthday: '2014-10-08',
  },
  {
    firstName: 'Melesa',
    lastName: 'Pavinese',
    email: 'mpavinese1@mlb.com',
    gender: false,
    birthday: '2012-08-14',
  },
  {
    firstName: 'Niel',
    lastName: 'Lammie',
    email: 'nlammie2@omniture.com',
    gender: false,
    birthday: '2019-09-18',
  },
  {
    firstName: 'Moyra',
    lastName: 'Von Der Empten',
    email: 'mvonderempten3@indiatimes.com',
    gender: true,
    birthday: '2008-04-03',
  },
  {
    firstName: 'Bill',
    lastName: 'MacKaig',
    email: 'bmackaig4@theglobeandmail.com',
    gender: true,
    birthday: '2009-02-01',
  },
  {
    firstName: 'Billy',
    lastName: 'Smallpeace',
    email: 'bsmallpeace5@hao123.com',
    gender: false,
    birthday: '2012-03-22',
  },
  {
    firstName: 'Danice',
    lastName: 'Swires',
    email: 'dswires6@mayoclinic.com',
    gender: true,
    birthday: '2006-01-15',
  },
  {
    firstName: 'Ashien',
    lastName: 'Trussman',
    email: 'atrussman7@phoca.cz',
    gender: true,
    birthday: '2019-07-12',
  },
  {
    firstName: 'Lonee',
    lastName: 'McLennan',
    email: 'lmclennan8@plala.or.jp',
    gender: true,
    birthday: '2017-12-10',
  },
  {
    firstName: 'Emmalee',
    lastName: 'Gurko',
    email: 'egurko9@auda.org.au',
    gender: false,
    birthday: '2016-10-15',
  },
  {
    firstName: 'Mandy',
    lastName: 'Padell',
    email: 'mpadella@typepad.com',
    gender: true,
    birthday: '2016-02-23',
  },
  {
    firstName: 'Arleyne',
    lastName: 'Pashley',
    email: 'apashleyb@noaa.gov',
    gender: true,
    birthday: '2020-06-30',
  },
  {
    firstName: 'Jozef',
    lastName: 'Tassaker',
    email: 'jtassakerc@scientificamerican.com',
    gender: true,
    birthday: '2015-01-15',
  },
  {
    firstName: 'Genevieve',
    lastName: 'Raund',
    email: 'graundd@joomla.org',
    gender: false,
    birthday: '2020-07-16',
  },
  {
    firstName: 'Viviyan',
    lastName: 'Saurat',
    email: 'vsaurate@sakura.ne.jp',
    gender: true,
    birthday: '2020-11-07',
  },
  {
    firstName: 'Agnesse',
    lastName: 'Stuchbery',
    email: 'astuchberyf@usda.gov',
    gender: true,
    birthday: '2006-10-19',
  },
  {
    firstName: 'Napoleon',
    lastName: 'Jales',
    email: 'njalesg@google.fr',
    gender: true,
    birthday: '2004-06-16',
  },
  {
    firstName: 'Krissy',
    lastName: 'Weaving',
    email: 'kweavingh@merriam-webster.com',
    gender: true,
    birthday: '2002-10-31',
  },
  {
    firstName: 'Halimeda',
    lastName: 'Shillam',
    email: 'hshillami@4shared.com',
    gender: true,
    birthday: '2017-01-19',
  },
  {
    firstName: 'Louie',
    lastName: 'Bottom',
    email: 'lbottomj@ftc.gov',
    gender: false,
    birthday: '2021-02-17',
  },
  {
    firstName: 'Zack',
    lastName: 'Hitter',
    email: 'zhitterk@google.de',
    gender: false,
    birthday: '2005-08-23',
  },
  {
    firstName: 'Reinold',
    lastName: 'Macklam',
    email: 'rmacklaml@bizjournals.com',
    gender: false,
    birthday: '2017-05-02',
  },
  {
    firstName: 'Curtis',
    lastName: 'Weatherdon',
    email: 'cweatherdonm@meetup.com',
    gender: false,
    birthday: '2000-04-19',
  },
  {
    firstName: 'Beniamino',
    lastName: 'Mungham',
    email: 'bmunghamn@geocities.com',
    gender: false,
    birthday: '2018-11-10',
  },
  {
    firstName: 'Phedra',
    lastName: 'Tankard',
    email: 'ptankardo@dion.ne.jp',
    gender: true,
    birthday: '2017-02-26',
  },
  {
    firstName: 'Lonnie',
    lastName: 'Murrell',
    email: 'lmurrellp@tumblr.com',
    gender: true,
    birthday: '2008-08-30',
  },
  {
    firstName: 'Wayne',
    lastName: 'Durnill',
    email: 'wdurnillq@rediff.com',
    gender: false,
    birthday: '2002-01-23',
  },
  {
    firstName: 'Giles',
    lastName: 'Lowten',
    email: 'glowtenr@nasa.gov',
    gender: true,
    birthday: '2023-03-01',
  },
  {
    firstName: 'Robby',
    lastName: 'Szymonowicz',
    email: 'rszymonowiczs@live.com',
    gender: true,
    birthday: '2012-08-31',
  },
  {
    firstName: 'Carin',
    lastName: 'Belly',
    email: 'cbellyt@globo.com',
    gender: true,
    birthday: '2013-05-07',
  },
  {
    firstName: 'Moyna',
    lastName: 'Kerswell',
    email: 'mkerswellu@comsenz.com',
    gender: false,
    birthday: '2014-09-23',
  },
  {
    firstName: 'Cristen',
    lastName: 'Broggetti',
    email: 'cbroggettiv@simplemachines.org',
    gender: true,
    birthday: '2018-09-29',
  },
  {
    firstName: 'Christy',
    lastName: 'Elphinstone',
    email: 'celphinstonew@wix.com',
    gender: false,
    birthday: '2006-11-04',
  },
  {
    firstName: 'Laurens',
    lastName: 'Risbrough',
    email: 'lrisbroughx@ed.gov',
    gender: false,
    birthday: '2011-12-17',
  },
  {
    firstName: 'Den',
    lastName: 'Longhorn',
    email: 'dlonghorny@imgur.com',
    gender: false,
    birthday: '2022-11-23',
  },
  {
    firstName: 'Diann',
    lastName: 'Murrum',
    email: 'dmurrumz@bloglines.com',
    gender: false,
    birthday: '2016-09-14',
  },
  {
    firstName: 'Dannie',
    lastName: 'Richardson',
    email: 'drichardson10@sciencedaily.com',
    gender: true,
    birthday: '2005-05-27',
  },
  {
    firstName: 'Jacqueline',
    lastName: 'Rennels',
    email: 'jrennels11@cornell.edu',
    gender: false,
    birthday: '2013-08-21',
  },
  {
    firstName: 'Timoteo',
    lastName: 'Tebbitt',
    email: 'ttebbitt12@tiny.cc',
    gender: false,
    birthday: '2009-10-23',
  },
  {
    firstName: 'Wolfie',
    lastName: 'Goodrich',
    email: 'wgoodrich13@barnesandnoble.com',
    gender: true,
    birthday: '2022-09-23',
  },
  {
    firstName: 'Marigold',
    lastName: 'Gardiner',
    email: 'mgardiner14@ft.com',
    gender: false,
    birthday: '2010-08-09',
  },
  {
    firstName: 'Diarmid',
    lastName: 'Bartoli',
    email: 'dbartoli15@umn.edu',
    gender: true,
    birthday: '2014-12-11',
  },
  {
    firstName: 'Marybelle',
    lastName: 'Bullan',
    email: 'mbullan16@toplist.cz',
    gender: false,
    birthday: '2009-02-19',
  },
  {
    firstName: 'Bondie',
    lastName: 'Sandall',
    email: 'bsandall17@amazonaws.com',
    gender: true,
    birthday: '2008-04-14',
  },
  {
    firstName: 'Salli',
    lastName: 'Porker',
    email: 'sporker18@jigsy.com',
    gender: false,
    birthday: '2013-05-25',
  },
  {
    firstName: 'Kimmi',
    lastName: 'Graundisson',
    email: 'kgraundisson19@cmu.edu',
    gender: true,
    birthday: '2016-09-03',
  },
  {
    firstName: 'Celisse',
    lastName: 'Bartomieu',
    email: 'cbartomieu1a@bigcartel.com',
    gender: true,
    birthday: '2010-06-08',
  },
  {
    firstName: 'Waring',
    lastName: 'Whife',
    email: 'wwhife1b@discuz.net',
    gender: true,
    birthday: '2008-11-06',
  },
  {
    firstName: 'Jephthah',
    lastName: 'Gynn',
    email: 'jgynn1c@phpbb.com',
    gender: false,
    birthday: '2012-12-10',
  },
  {
    firstName: 'Tyler',
    lastName: 'Horsefield',
    email: 'thorsefield1d@list-manage.com',
    gender: false,
    birthday: '2009-04-04',
  },
  {
    firstName: 'Melessa',
    lastName: 'Scrymgeour',
    email: 'mscrymgeour1e@usgs.gov',
    gender: true,
    birthday: '2005-01-12',
  },
  {
    firstName: 'Rica',
    lastName: 'Ledwich',
    email: 'rledwich1f@creativecommons.org',
    gender: false,
    birthday: '2020-03-25',
  },
  {
    firstName: 'Gale',
    lastName: 'Steven',
    email: 'gsteven1g@fda.gov',
    gender: true,
    birthday: '2006-02-03',
  },
  {
    firstName: 'Cort',
    lastName: 'Eastcourt',
    email: 'ceastcourt1h@multiply.com',
    gender: true,
    birthday: '2019-04-23',
  },
  {
    firstName: 'Brunhilde',
    lastName: 'Heugh',
    email: 'bheugh1i@goodreads.com',
    gender: false,
    birthday: '2006-11-15',
  },
  {
    firstName: 'Verne',
    lastName: 'Danielovitch',
    email: 'vdanielovitch1j@un.org',
    gender: true,
    birthday: '2002-12-24',
  },
  {
    firstName: 'Far',
    lastName: 'Cantopher',
    email: 'fcantopher1k@auda.org.au',
    gender: true,
    birthday: '2008-10-29',
  },
  {
    firstName: 'Gerhardt',
    lastName: 'Treadgall',
    email: 'gtreadgall1l@joomla.org',
    gender: false,
    birthday: '2004-07-13',
  },
  {
    firstName: 'Myrtle',
    lastName: 'Tertre',
    email: 'mtertre1m@elegantthemes.com',
    gender: false,
    birthday: '2020-03-04',
  },
  {
    firstName: 'Martyn',
    lastName: 'Nuth',
    email: 'mnuth1n@shop-pro.jp',
    gender: true,
    birthday: '2008-09-01',
  },
  {
    firstName: 'Taber',
    lastName: 'Garry',
    email: 'tgarry1o@marriott.com',
    gender: true,
    birthday: '2008-03-12',
  },
  {
    firstName: 'Patrick',
    lastName: 'Sturgis',
    email: 'psturgis1p@oaic.gov.au',
    gender: false,
    birthday: '2015-05-16',
  },
  {
    firstName: 'Bonnie',
    lastName: 'Cull',
    email: 'bcull1q@wired.com',
    gender: true,
    birthday: '2010-08-20',
  },
  {
    firstName: 'Gabey',
    lastName: 'Jedrzejkiewicz',
    email: 'gjedrzejkiewicz1r@usgs.gov',
    gender: true,
    birthday: '2003-08-25',
  },
  {
    firstName: 'Erinna',
    lastName: 'Folliott',
    email: 'efolliott1s@dedecms.com',
    gender: false,
    birthday: '2023-03-11',
  },
  {
    firstName: 'Randolf',
    lastName: 'Oake',
    email: 'roake1t@t-online.de',
    gender: true,
    birthday: '2010-12-14',
  },
  {
    firstName: 'Margaret',
    lastName: 'Tourry',
    email: 'mtourry1u@nydailynews.com',
    gender: false,
    birthday: '2003-03-19',
  },
  {
    firstName: 'Larine',
    lastName: 'Bridewell',
    email: 'lbridewell1v@google.com.au',
    gender: false,
    birthday: '2016-10-23',
  },
  {
    firstName: 'Moss',
    lastName: 'Rizzotto',
    email: 'mrizzotto1w@ftc.gov',
    gender: true,
    birthday: '2012-07-27',
  },
  {
    firstName: 'Adamo',
    lastName: 'Gritland',
    email: 'agritland1x@fastcompany.com',
    gender: true,
    birthday: '2000-06-26',
  },
  {
    firstName: 'Sada',
    lastName: 'Shills',
    email: 'sshills1y@thetimes.co.uk',
    gender: false,
    birthday: '2003-05-20',
  },
  {
    firstName: 'Farleigh',
    lastName: 'Trewhela',
    email: 'ftrewhela1z@slate.com',
    gender: true,
    birthday: '2020-01-26',
  },
  {
    firstName: 'Eleanor',
    lastName: 'Weller',
    email: 'eweller20@aol.com',
    gender: false,
    birthday: '2016-08-22',
  },
  {
    firstName: 'Eziechiele',
    lastName: 'Frizzell',
    email: 'efrizzell21@wufoo.com',
    gender: true,
    birthday: '2023-01-26',
  },
  {
    firstName: 'Jere',
    lastName: 'Womersley',
    email: 'jwomersley22@diigo.com',
    gender: true,
    birthday: '2020-09-11',
  },
  {
    firstName: 'Mayne',
    lastName: 'Samme',
    email: 'msamme23@fotki.com',
    gender: false,
    birthday: '2001-08-14',
  },
  {
    firstName: 'Nedda',
    lastName: 'Morrice',
    email: 'nmorrice24@51.la',
    gender: true,
    birthday: '2007-12-17',
  },
  {
    firstName: 'Oriana',
    lastName: 'Gandy',
    email: 'ogandy25@ucsd.edu',
    gender: true,
    birthday: '2010-07-11',
  },
  {
    firstName: 'Nickey',
    lastName: 'Meas',
    email: 'nmeas26@usnews.com',
    gender: false,
    birthday: '2011-12-05',
  },
  {
    firstName: 'Josefina',
    lastName: 'Bradman',
    email: 'jbradman27@opensource.org',
    gender: true,
    birthday: '2019-04-25',
  },
  {
    firstName: 'Jamison',
    lastName: 'Pridding',
    email: 'jpridding28@mtv.com',
    gender: false,
    birthday: '2017-07-17',
  },
  {
    firstName: 'Cristine',
    lastName: 'Skotcher',
    email: 'cskotcher29@vinaora.com',
    gender: true,
    birthday: '2014-02-25',
  },
  {
    firstName: 'Travers',
    lastName: 'Legge',
    email: 'tlegge2a@gnu.org',
    gender: false,
    birthday: '2000-10-20',
  },
  {
    firstName: 'Pauletta',
    lastName: 'Bellwood',
    email: 'pbellwood2b@bloglines.com',
    gender: true,
    birthday: '2018-11-03',
  },
  {
    firstName: 'Mirna',
    lastName: 'Gallaccio',
    email: 'mgallaccio2c@mozilla.com',
    gender: false,
    birthday: '2022-09-18',
  },
  {
    firstName: 'Trude',
    lastName: 'Woolnough',
    email: 'twoolnough2d@netvibes.com',
    gender: true,
    birthday: '2013-11-30',
  },
  {
    firstName: 'Rhianon',
    lastName: 'Ettritch',
    email: 'rettritch2e@java.com',
    gender: false,
    birthday: '2000-08-10',
  },
  {
    firstName: 'Danette',
    lastName: 'Warren',
    email: 'dwarren2f@omniture.com',
    gender: false,
    birthday: '2012-09-17',
  },
  {
    firstName: 'Gerry',
    lastName: 'Boughtflower',
    email: 'gboughtflower2g@abc.net.au',
    gender: false,
    birthday: '2022-10-04',
  },
  {
    firstName: 'Olivia',
    lastName: 'Parbrook',
    email: 'oparbrook2h@canalblog.com',
    gender: false,
    birthday: '2003-11-27',
  },
  {
    firstName: 'Heinrick',
    lastName: 'Robelin',
    email: 'hrobelin2i@nymag.com',
    gender: true,
    birthday: '2010-11-21',
  },
  {
    firstName: 'Hamnet',
    lastName: 'Last',
    email: 'hlast2j@ifeng.com',
    gender: false,
    birthday: '2009-10-13',
  },
  {
    firstName: 'Michail',
    lastName: 'Guerner',
    email: 'mguerner2k@hatena.ne.jp',
    gender: true,
    birthday: '2015-04-20',
  },
  {
    firstName: 'Doralyn',
    lastName: 'Manwell',
    email: 'dmanwell2l@de.vu',
    gender: true,
    birthday: '2011-08-05',
  },
  {
    firstName: 'Skyler',
    lastName: 'Tomsen',
    email: 'stomsen2m@tiny.cc',
    gender: true,
    birthday: '2016-10-06',
  },
  {
    firstName: 'Julius',
    lastName: 'Gaddie',
    email: 'jgaddie2n@columbia.edu',
    gender: false,
    birthday: '2019-12-31',
  },
  {
    firstName: 'Saba',
    lastName: 'Housby',
    email: 'shousby2o@infoseek.co.jp',
    gender: false,
    birthday: '2018-05-15',
  },
  {
    firstName: 'Gustaf',
    lastName: 'Goodie',
    email: 'ggoodie2p@hubpages.com',
    gender: true,
    birthday: '2013-10-15',
  },
  {
    firstName: 'Erhart',
    lastName: 'Borges',
    email: 'eborges2q@cmu.edu',
    gender: true,
    birthday: '2019-08-12',
  },
  {
    firstName: 'Sergent',
    lastName: 'Oager',
    email: 'soager2r@google.es',
    gender: false,
    birthday: '2011-09-11',
  },
]

let _users = []
users.forEach((item) =>
  _users.find((_item) => _item.email === item.email) ? null : _users.push(item)
)
users = _users

users = users.map((item) => ({
  ...item,
  username: (item.firstName + '-' + item.lastName).replace(/\s+/g, '').toLowerCase(),
  password: '12345678',
  avatar: 'https://picsum.photos/300/300',
  photos: [
    'https://picsum.photos/200/300',
    'https://picsum.photos/300/300',
    'https://picsum.photos/400/300',
  ],
}))

window.data = window.data || {}
window.data.users = users
